AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Task Definition and Service for Image Assurance Scanner and internal ECR Repo to pull the Image
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CloudGuard
        Parameters:
          - Dome9PasswordSecret
          - CloudGuardScanningEnvironmentId
          - CloudGuardApiKey
          - RegistryAgentMode
      - Label:
          default: AWS
        Parameters:
          - ExecutionRole
          - TaskRole
          - ECSClusterArn
          - ReplicaCount
          - SubnetIds
          - Cpu
          - Memory
          - Image
    ParameterLabels:
      Dome9PasswordSecret:
        default: Dome9 Password Secret ARN
      CloudGuardScanningEnvironmentId:
        default: D9 AWS Environment ID
      ExecutionRole:
        default: Task IAM Role ARN for the Task Execution
      TaskRole:
        default: Task IAM Role ARN for the Task
      CloudGuardApiKey:
        default: CloudGuard API Key Id
      ECSClusterArn:
        default: ECS Cluster Arn
      ReplicaCount:
        default: Number of Replicas
      SubnetIds:
        default: The public subnets of the cluster
      RegistryAgentMode:
        default: Registry Agent Mode Option <scan, list>
      Cpu:
        default: The number of cpu units used by the ecs scanner/lister task
      Memory:
        default: The amount (in MiB) of memory used by the ecs scanner/lister task
      Image:
        default: The image to be used for the task
Parameters:
  Dome9PasswordSecret:
    Type: String
    Description: ARN for Dome9 Password credentials (arn:aws:secretsmanager:*:*:secret:*)
    AllowedPattern: '^arn:aws:secretsmanager:[A-Za-z0-9-:]+$|^arn:aws-cn:secretsmanager:[A-Za-z0-9-:]+$'
  CloudGuardScanningEnvironmentId:
    Type: String
    Description: The CloudGuard environment id (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
  ExecutionRole:
    Type: String
    Description: ARN for Execution Role (arn:aws:iam::*:role/*)
    AllowedPattern: '^arn:aws:iam:[A-Za-z0-9-:]+role[A-Za-z0-9-:\/]+$|^arn:aws-cn:iam:[A-Za-z0-9-:]+role[A-Za-z0-9-:\/]+$'
  TaskRole:
    Type: String
    Description: ARN for Execution Role (arn:aws:iam::*:role/*)
    AllowedPattern: '^arn:aws:iam:[A-Za-z0-9-:]+role[A-Za-z0-9-:\/]+$|^arn:aws-cn:iam:[A-Za-z0-9-:]+role[A-Za-z0-9-:\/]+$'
  CloudGuardApiKey:
    Type: String
    Description: CloudGuard API Key
  ECSClusterArn:
    Type: String
    Description: ARN for ECS Cluster (arn:aws:ecs:*:cluster/*)
    AllowedPattern: '^arn:aws:ecs:[A-Za-z0-9-:]+\:cluster\/[A-Za-z0-9-:]+$|^arn:aws-cn:ecs:[A-Za-z0-9-:]+\:cluster\/[A-Za-z0-9-:]+$'
  ReplicaCount:
    Type: Number
    Default: 1
    Description: Number of replicas
  SubnetIds:
    Type: CommaDelimitedList
    Description: >-
      The public subnet of the cluster. The cluster's public IPs will be
      generated from this subnet. The subnet's route table must have 0.0.0.0/0
      route to Internet Gateway
  RegistryAgentMode:
    Type: String
    Description: Registry Agent Mode Option <scan, list> to select if the Image Engine is a Scanner or Image Lister
    AllowedValues:
      - scan
      - list
  Cpu:
    Description: The number of cpu units used by the ecs scanner/lister task
    Type: String
    Default: 1024
    AllowedValues: [ 1024, 2048, 4096, 8192, 16384 ]
  Memory:
    Description: The amount (in MiB) of memory used by the ecs scanner/lister task
    Type: String
    Default: 2048
  Image:
    Type: String
    Description: The image to be used for the task
    Default: '058264191330.dkr.ecr.ap-east-1.amazonaws.com/unique-ecr-repo-20240629160036:consec-imagescan-engine-2.28.0'
Resources:
  ConsecEcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - EntryPoint:
            - /central_agent
          PortMappings: []
          Command: []
          Environment:
            - Name: CLOUDGUARD_REGION
              Value: us # valid values: us, us9, us7, eu1, ap1, ap2, ap3, cace1
            - Name: CP_KUBERNETES_CLUSTER_ID
              Value: !Ref CloudGuardScanningEnvironmentId
            - Name: CHKP_CLOUDGUARD_ID
              Value: !Ref CloudGuardApiKey
            - Name: REGISTRY_AGENT_MODE
              Value: !Ref RegistryAgentMode
            - Name: DOME9_URL
              Value: https://api-cpx.dome9.com # valid values: https://api-cpx.eu1.dome9.com, https://api-cpx.ap1.dome9.com, https://api-cpx.ap2.dome9.com, https://api-cpx.ap3.dome9.com, https://api-cpx.cace1.dome9.com, https://api-cpx.us9.falconetix.com, https://api-cpx.us7.falconetix.com, https://api-cpx.dome9.com
            - Name: REGISTRY_ONLY
              Value: true
          Secrets:
            - Name: CHKP_CLOUDGUARD_SECRET
              ValueFrom: !Ref Dome9PasswordSecret
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: fargate/consec
              awslogs-region: !Sub '${AWS::Region}'
              awslogs-stream-prefix: consec
              awslogs-create-group: 'true'
          Image: !Ref Image
          Name: consec-imagescan-container
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      Family: !Join ['', ['consec-imagescan-task-definition-', !Ref RegistryAgentMode]]
  ConsecEcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSClusterArn
      DesiredCount: !Ref ReplicaCount
      TaskDefinition: !Ref ConsecEcsTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
      LaunchType: FARGATE
    Metadata: { }
    DependsOn:
      - ConsecEcsTaskDefinition
